### ISSUE TITLE
Gyroflow not showing up in Davinci Resolve Studio 18 on Linux

### ISSUE THREAD

**Issue by FabulousSoldier** [gyroflow/gyroflow-ofx#40] opened 2023-07-17 15:40 UTC
I installed the plugin (DaVinci Resolve/OpenFX v1.2.2) as described in the documentation on Arch Linux:
https://docs.gyroflow.xyz/app/video-editor-plugins/davinci-resolve-openfx

In Resolve it shows up as "Loaded successfully" and it is enabled:
![Screenshot_20230717_172919](https://github.com/gyroflow/gyroflow-ofx/assets/4923534/41c88688-58a8-49f7-9dd8-6ad8c6aed4b2)

But the plugin is not showing up in the list under effects:
![Screenshot_20230717_172946](https://github.com/gyroflow/gyroflow-ofx/assets/4923534/d77a3b6e-3746-4c89-a686-f0bcfe1fb4ff)

When searching for it it also does not show up:
![Screenshot_20230717_173118](https://github.com/gyroflow/gyroflow-ofx/assets/4923534/3407da07-8688-41df-bdbb-b4e81e9f1741)

In Fusion it is also not visible.

**Comment by DavidNorena** [comment] 2023-08-23 21:50
Did you manage to resolve it ? the issue is in my linux machine as well l @AdrianEddy any way to debug and try to find the issue ?

**Comment by FabulousSoldier** [comment] 2023-08-24 07:50
Unfortunately no. I am running  Davinci Resolve Studio 18.5.1 now on Arch Linux and the Gyroflow is still not showing up even thought it  is "Loaded successfully" and enabled in the Video Plugin preferences of Resolve.

I tried reinstalling the plugin, restarting Resolve & my PC, but nothing has worked so far.

**Comment by BettaGeorge** [comment] 2023-09-28 22:44
Just reporting that I have the exact same problem (still) with Resolve Studio 18.5b41 on Arch with all updates. Restarting my computer and reinstalling the plugin change nothing. Changing the permissions on the unpacked archive or the folder /usr/OFX does nothing. Choosing a different path for the video plugins does nothing.

To reiterate, Resolve shows the plugin as "loaded successfully" and the little tick mark in front of it is enabled, the plugin just does not show up in the list of effects and is also not accessible via the search function.

Is anyone working on this issue, or is there some workaround to apply an unlisted effect? Reencoding my raw files from Gyroflow before putting them into Resolve takes days for some projects.

**Comment by AdrianEddy** [comment] 2023-10-17 20:34
please test latest dev build: https://gyroflow.xyz/devbuild/

**Comment by AdrianEddy** [comment] 2023-10-18 22:26
Should be fixed in latest dev build https://gyroflow.xyz/devbuild/

**Closed by AdrianEddy** 2023-10-18 22:26 UTC
